security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        users_in_memory: { memory: null }
        users_in_database:
            entity:
                class: App\Entity\User
                property: email

    role_hierarchy:
        ROLE_ADMIN: ROLE_OWNER
        ROLE_OWNER: ROLE_USER
        ROLE_USER:

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: users_in_database
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                success_handler: App\Security\LoginSuccessHandler
            logout:
                path: app_logout
                # target: app_any_route (optional)

    access_control:
        - { path: ^/dashboard, roles: ROLE_USER }
        - { path: ^/offers, roles: ROLE_USER }
        - { path: ^/admin, roles: [ROLE_ADMIN, ROLE_OWNER] }
        - { path: ^/profil, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10

services:
    App\Security\LoginSuccessHandler:
        arguments:
            $router: '@router'
